### ISSUE TITLE
maven install fails with plugincontainerexception

### ISSUE THREAD

**Issue by codestroll** [nacho4d/rest_to_pdf_example#1]
I was trying to setup swagger as mentioned in the link: https://github.com/nacho4d/rest_to_pdf_example
When I run install, it throws the below exception.
Number of foreign imports: 1 import: Entry[import from realm ClassRealm[maven.api, parent: null]]

at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:168)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
... 20 more
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing io.github.swagger2markup:swagger2markup-maven-plugin:1.0.1:convertSwagger2markup: org/apache/commons/beanutils/DynaBean

**Comment by nacho4d** [comment]
Sorry for the late response.
I just cloned my repo, and simply run `mvn package` and it worked as expected. I also tried `mvn install`. I wonder what is different from yours...

I am using Apache Maven 3.3.9 (`mvn --version`)

**Comment by nacho4d** [comment]
Same as http://stackoverflow.com/questions/41334300/maven-install-fails-with-plugincontainerexception-defaultbuildpluginmanager-exe
